apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: redis
  name: redis
spec:
  selector:
    matchLabels:
      component: redis
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - image: redis:alpine3.20
        name: redis
        ports:
        - containerPort: 6379
