apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-slave-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/data"
