apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fortune
  name: fortune
spec:
  volumes:
    - name: content
      emptyDir:
        sizeLimit: 100Mi
  containers:
  - image: phan456/fortune-writer:3.0
    name: fortune
    volumeMounts:
      - name: content
        mountPath: /var/local/output 
    resources: {}
  - image: nginx:alpine
    name: nginx
    volumeMounts:
      - name: content
        mountPath: /usr/share/nginx/html
        readOnly: true
    ports:
      - name: http
        containerPort: 80
