apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
  selector:
    app: kubia
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubia
spec:
  serviceName: kubia
  replicas: 2
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - image: luksa/kubia-pet
          name: kubia
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /var/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: ""
        resources:
          requests:
            storage: 10Mi
        accessModes:
          - ReadWriteOnce
