apiVersion: v1
kind: Pod
metadata:
  name: hello-cm
  labels:
    app: application
spec:
  containers:
    - image: phan456/hello-cm:v2
      name: hello-cm
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: postgres-config
          prefix: POSTGRES_
      env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: postgres
          
---
apiVersion: v1
kind: Pod
metadata: 
  name: postgres
  labels:
    app: db
spec:
  containers:
    - image: postgres:alpine
      name: postgres
      ports:
        - containerPort: 5432
      envFrom:
        - secretRef:
            name: postgres-config
          prefix: POSTGRES_
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
