apiVersion: batch/v1
kind: Job
metadata:
  name: sync-master-data
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: sync-master-data
          image: postgres:11-alpine
          command:
            [
              "sh",
              "-c",
              'rm -rf /var/lib/slave-postgresql/data/* && PGPASSWORD="postgres" pg_basebackup -h postgres-master -p 5432 -D /var/lib/slave-postgresql/data -U repuser -Xs -R -vP',
            ]
          volumeMounts:
            - mountPath: /var/lib/slave-postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-slave
