apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: v1.0.0
  template:
    metadata:
      labels:
        app: my-app
        version: v1.0.0
    spec:
      containers:
      - image: argoproj/rollouts-demo:green
        name: my-app
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-v1
spec:
  selector:
    app: my-app
    version: v1.0.0
  ports:
  - name: http
    port: 8080
    targetPort: http
